baseurl      = "bloomsa.github.io"
title        = "My Site"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "dev, dog person"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # The theme is respecting the prefers-color-scheme of the operating system. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true

  # Metadata mostly used in document's head
  description = "My website"
  keywords = "homepage, blog"
  images = [""]

  # Social Icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/bloomsa"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/sam-bloomquist-287339157/"

  [[params.social]]
    name = "email"
    url = "mailto:bloomquist.sam@gmail.com"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Sam Bloomquist"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "Sam Bloomquist's website"

    [languages.en.params.logo]
      logoText = "bloomsa"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About Me"
    url        = "/about"